### PR TITLE
feat: web clients

### PR DESCRIPTION
**Pull request by jeswr**

### CODE REVIEW

**Comment by jeswr** [comment]
@rubensworks - I'm trying to figure why these CI tests are still failing in the deployment of the web-clients. It would seem that the `web-clients` package expects the reasoning components to be in its dependencies; do I need to add them as dependencies over in that package?

Once I get this deployed I'll add a research page as suggested in https://github.com/comunica/comunica/pull/979#issuecomment-1099893888

**Comment by rubensworks** [comment]
Everything looks good to me here at first glance. Don't really understand why it's giving this error. Everything looks the same as in the link-traversal repo.
Does it work correctly if you just build it locally?

**Comment by jeswr** [comment]
Yes - still gettting this issue @rubensworks .

I also tried adding the packages listed as missing to the `config-reasoning` dependencies; but the problem persists.

**Comment by rubensworks** [comment]
Just to check that nothing major has changed in the workings of npx or webpack, could you try locally building a link traversal web client?

If that works, then I would suggest going over the differences between those two projects, as there must be one in that case.

**Comment by jeswr** [comment]
> could you try locally building a link traversal web client?

This works fine

> going over the differences

I'm struggling to find anything at the moment - will re-visit this later but my best guess is a missing dev-dep somewhere

**Comment by jeswr** [comment]
Now fixed the dependency errors but now getting a weird error around the `sed` command having an unknown option to `s` event though I cannot see the `s` option being used @rubensworks .

**Comment by rubensworks** [comment]
Perhaps it's line 11 or 18 in build-web-clients.sh? Maybe some $id value is invalid somehow?

**Pull request merged**
